### ISSUE TITLE
New primitives from hugging face are slower than built-in text encoder primitives.

### ISSUE THREAD

**Issue by laibamehnaz** [VIDA-NYU/alpha-automl#33]
I have added two language models as two new primitives: [ELECTRA](https://huggingface.co/docs/transformers/model_doc/electra) and [ROBERTA(domain adapted for sentiment analysis)](https://huggingface.co/allenai/reviews_roberta_base). 
However, these models seem to be much slower than built-in primitives but score high when given the appropriate amount of time to train. 

For example:

1. When timebound = 10 and SBATCH --time=00:30:00:
_My primitive is call MyEmbedder() here:_

![image](https://user-images.githubusercontent.com/36405283/234137907-1023916d-4677-459c-935e-36d1a9361993.png)

2. When timebound = 40 and SBATCH —time=04:00:00:
_My primitive is call MySentimentEmbedder() here:_

![image](https://user-images.githubusercontent.com/36405283/234137992-e53caec3-d5cc-414f-b4b8-4e13c9fba5c4.png)

My sbatch script is: 
```
#!/bin/bash
  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=2
#SBATCH --time=04:00:00
#SBATCH --mem=128GB
#SBATCH --job-name=torch
#SBATCH --output=4hours.out

module purge

singularity exec \
            --overlay /scratch/lm4428/my_env/overlay-50G-10M.ext3:rw \
            /scratch/work/public/singularity/cuda11.2.2-cudnn8-devel-ubuntu20.04.sif \
            /bin/bash -c "source /ext3/env.sh; python /scratch/lm4428/d3m_latest/alpha-automl/examples/adding_new_primitives_huggingface.py"
```

Is there a way I can decrease the amount of time it takes for these primitives?

**Comment by laibamehnaz** [comment]
Added [batching](https://github.com/VIDA-NYU/alpha-automl/blob/f19a2a7210557d0bed9864b462d492ecd36f5d89/alpha_automl/wrapper_primitives/huggingface.py#LL37C13-L37C18) while generating the embeddings, moved the embeddings per batch to the [cpu](https://github.com/VIDA-NYU/alpha-automl/blob/f19a2a7210557d0bed9864b462d492ecd36f5d89/alpha_automl/wrapper_primitives/huggingface.py#L57), and cleared the [cache](https://github.com/VIDA-NYU/alpha-automl/blob/f19a2a7210557d0bed9864b462d492ecd36f5d89/alpha_automl/wrapper_primitives/huggingface.py#L59)
Works fine after making these changes. All pipelines are generated within the given time frame.

**Comment by roquelopez** [comment]
Fixed in https://github.com/VIDA-NYU/alpha-automl/pull/35.
