### ISSUE TITLE
Not able to retain the module name as fasttext

### ISSUE THREAD

**Issue by madhuripujari95** [VIDA-NYU/alpha-automl#39]
I'm not able to retain the module name as fasttext.py due to the following issue. I think it is because my module name and the main fasttext module are the same name. 

![image](https://github.com/VIDA-NYU/alpha-automl/assets/94725022/a928b242-c900-4a97-9651-b44f1f2fde55)

**Comment by roquelopez** [comment]
This was fixed using the full import path.
