### ISSUE TITLE
examples/adding_huggingface_primitives.ipynb missing import?

### ISSUE THREAD

**Issue by bkj** [VIDA-NYU/alpha-automl#51]
Hello --

In `examples/adding_huggingface_primitives.ipynb`, I'm getting an error on 
```
from alpha_automl.wrapper_primitives.huggingface import HuggingfaceInterface
```
Is that function deprecated?  Should it maybe be changed to `HuggingfaceEmbedder` as per https://github.com/VIDA-NYU/alpha-automl/blob/devel/examples/adding_new_primitives_huggingface.py#L6

Thanks!

**Comment by roquelopez** [comment]
Thanks for opening the issue. You are right, we updated the example. This is fixed in #58.
