### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by allandclive** [VIDA-NYU/alpha-automl#74]
Can't Import Alpha AutoML

from alpha_automl import AutoMLClassifier
import pandas as pd

output
`ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from alpha_automl import AutoMLClassifier
      2 import pandas as pd

File ~\miniconda3\envs\alpha\Lib\site-packages\alpha_automl\__init__.py:3
      1 __version__ = '0.2.0'
----> 3 from .automl_api import AutoMLClassifier, AutoMLRegressor

File ~\miniconda3\envs\alpha\Lib\site-packages\alpha_automl\automl_api.py:7
      5 import pandas as pd
      6 from sklearn.preprocessing import LabelEncoder
----> 7 from alpha_automl.automl_manager import AutoMLManager
      8 from alpha_automl.scorer import make_scorer, make_splitter, make_str_metric
      9 from alpha_automl.utils import make_d3m_pipelines

File ~\miniconda3\envs\alpha\Lib\site-packages\alpha_automl\automl_manager.py:6
      4 from multiprocessing import set_start_method
      5 from alpha_automl.utils import sample_dataset, is_equal_splitting
----> 6 from alpha_automl.scorer import make_splitter, score_pipeline
      7 from alpha_automl.pipeline_synthesis.setup_search import search_pipelines as search_pipelines_proc
     10 USE_AUTOMATIC_GRAMMAR = False

File ~\miniconda3\envs\alpha\Lib\site-packages\alpha_automl\scorer.py:4
      2 import datetime
      3 import numpy as np
----> 4 from sklearn.metrics import SCORERS, get_scorer, make_scorer as make_scorer_sk
      5 from sklearn.model_selection import BaseCrossValidator, KFold, ShuffleSplit, train_test_split, cross_val_score
      6 from sklearn.model_selection._split import BaseShuffleSplit, _RepeatedSplits

ImportError: cannot import name 'SCORERS' from 'sklearn.metrics' (C:\Users\USER\miniconda3\envs\alpha\Lib\site-packages\sklearn\metrics\__init__.py`

**Comment by roquelopez** [comment]
Hi @allandclive, thanks for opening the issue. That's an issue in sklearn ('SCORERS is no longer available in newer versions of sklearn). Please, use the devel version of Alpha-AutoML (which does not use SCORERS). To install it, run: `pip install git+https://github.com/VIDA-NYU/alpha-automl@devel`. We will have a new release on Pypi by the end of this week.
