### ISSUE TITLE
Support for latest Python and core libraries

### ISSUE THREAD

**Issue by aecio** [VIDA-NYU/alpha-automl#78]
Need to make sure that we support the latest Python (3.11) and recent versions of core libraries. We need to remove the version restrictions of some libraries and make sure everything works fine:
- scipy<=1.9.3
- numpy<=1.24.3

TODO:
- [ ] Upgrade the `requirements.txt` file to remove restrictions
- [ ] Upgrade Dockerfile to use Python 3.11
- [ ] Make GitHub CI run tests on multiple Python versions
- [ ] Test and fix any bugs found, if any

**Comment by EdenWuyifan** [comment]
We need certain restrictions for timeseries and nlp tasks. Some version control shouldn't be removed

**Comment by roquelopez** [comment]
Since they are restrictions for timeseries and nlp tasks, I think we should relax the versions in `requirements.txt ` but add the constraints in [extra_requirements.txt](https://github.com/VIDA-NYU/alpha-automl/blob/devel/extra_requirements.txt)

**Comment by EdenWuyifan** [comment]
Ok, one of the restrictions in mxnet requires lower version numpy's np.bool method in time-series forecast tasks. Refers to this:
https://stackoverflow.com/questions/74893742/how-to-solve-attributeerror-module-numpy-has-no-attribute-bool

![Screenshot from 2023-11-06 13-51-09](https://github.com/VIDA-NYU/alpha-automl/assets/43869961/7718dff9-9dd1-4865-83be-ed8e2fe041a3)
